Repository CropAi/Data-Modeling, pull requests merged in 2020-03, with the labels that each got.

#12 Documentation on Transfer Learning
  transfer learning.md
Labels: beginner, documentation, gssoc20

#11 #3 Requirements Text file
  Requirements.txt
Labels: beginner, gssoc20

#16 Proper requirements.txt
  .gitignore
  Requirements.md
  requirements.txt
Labels: beginner, gssoc20

#18 #13 Tensorflow setup added
  README.md
Labels: beginner, gssoc20

#32 Setting up Tensorflow on Windows and Keras implementation
  CropAI_Keras.ipynb
  README.md
  requirements.txt
  setting-up-tensorflow/installing-tensorflow-on-windows.md
Labels: documentation, easy, gssoc20, hard

#29 Fixes Issue #24
  label_binarizer_instance.py
Labels: beginner, gssoc20

#30 Cvt image to array@abhishekgupta368
  Image_To_array.py
  requirements.txt
Labels: beginner, gssoc20

#33 Fixed issue #21(load 200 images from each folder)
  README.md
  load_images.py
Labels: beginner, gssoc20

#36 Fixed #35 (Refine Readme file)
  README.md
Labels: documentation, easy, gssoc20

#42 windows installation commands updated
  README.md
Labels: documentation, easy, gssoc20

#28 #19 Build a model using keras
  Crop_AI_Keras.ipynb
  kaggle.json
Labels: gssoc20, hard

#43 Uploading Dataset on Google Colab
  Upload Kaggle Dataset in colab.ipynb
Labels: beginner, documentation, gssoc20

#51 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: beginner, documentation, gssoc20

#50 Added ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: gssoc20, medium

#34 Siamese model@abhishekgupta368
  Image_To_array.py
  Siamese_model.ipynb
Labels: gssoc20, hard

#57 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: beginner, gssoc20

#54 image segmentation opencv
  Spot Detection.ipynb
  requirements.txt
Labels: gssoc20, medium

#66 Typos Fixed
  README.md
Labels: beginner, gssoc20

#44 Fix to issue #38 (AlexNet)
  CropAI_AlexNet.ipynb
Labels: gssoc20, medium

#68 added_eda
  Exploratory Data Analysis.ipynb
Labels: beginner, documentation, gssoc20

#63 Image segmentation using Kmeans
  .gitignore
  Spot_Detection_KMeans.ipynb
Labels: gssoc20, medium

#73 Fix to issue #71
  LoadH5.py
Labels: easy, gssoc20

#70 plot
  .gitignore
  Crop_AI_Keras_plot.ipynb
  Spot_Detection_KMeans.ipynb
Labels: beginner, gssoc20

#72 load_file_gd
  encoder.pkl
  label_images.py
Labels: easy, gssoc20

#60 Tidy up repository!!
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/TensorFlowLinux.md
  docs/TensorFlowWindows.md
  docs/transfer_learning.md
  modules/label_binarizer_instance.py
Labels: beginner, gssoc20

#75 predict test image
  Predict Test Images_New.ipynb
Labels: beginner, gssoc20
