Repository CropAi/Data-Modeling, pull requests merged in 2020-05, with the labels that each got.

#81 Reading Image #1 #7
  Linux_Installation/TensorFlowLinux.md
  Notebooks/Predict Test Images_New.ipynb
  Notebooks/Siamese_model.ipynb
  Notebooks/Spot Detection.ipynb
  Notebooks/Spot_Detection_KMeans.ipynb
  Notebooks/Upload Kaggle Dataset in colab.ipynb
  Windows_Installation/TensorFlowWindows.md
  cropai/modules/cropai.py
  cropai/modules/setup.py
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/TensorFlowLinux.md
  docs/TensorFlowWindows.md
  docs/transfer_learning.md
  encoder.pkl
  label_images.py
  modules/label_binarizer_instance.py
  modules/load_images.py
Labels: easy, gssoc20

#26 Cross validation #2
  cross_valid/cross_valid/README.md
  cross_valid/cross_valid/__init__.py
  cross_valid/cross_valid/cross_valid.py
  cross_valid/setup.py
Labels: beginner, gssoc20

#86 Unet model
  Unet Model/README.md
  Unet Model/Unet.ipynb
Labels: gssoc20, medium
